# I'm just gonna see if I can write a quick and dirty kepler-planet function thing

In [18]:
filename = 'planets_2019.07.30_19.22.04.csv'

In [19]:
import pandas as pd
import numpy as np

In [20]:
planets = pd.read_csv(filename, 
                     sep=",", comment="#")

In [21]:
# orig function:
def read_kepler_data(fileLocation):
    names = ('RowID', 'SysName', 'planetLetter', 'NumberOfPlanets', 'Porb', 
             'ePorbU', 'ePorbL',       'a',             'ea',       'ecc', 
             'eeccU',    'eeccL',    'Incl',           'eInclU',    'eInclL', 
             'pMass',   'epMassU', 'epMassL',          'pMassType', 'sMass', 
             'esMass',  'sRadius', 'esRadiusU',       'esRadiusL',  'tTime', 
             'etTimeU', 'etTimeL')
    formats = ('f4',       'S12',     'S2',               'f4',        'f4',
               'f4',       'f4',      'f4',               'f4',        'f4',
               'f4',       'f4',      'f4',               'f4',        'f4',
               'f4',       'f4',      'f4',               'S8',        'f4',
               'f4',       'f4',      'f4',               'f4',        'f4', 
               'f4',       'f4')
    kepler_data = np.genfromtxt(fileLocation, 
                                comments='#', 
                                delimiter=',', 
                                dtype={'names':names, 
                                       'formats':formats})
    return kepler_data


In [22]:
planets['pl_hostname'].unique()

array(['11 Com', '11 UMi', '14 And', ..., 'tau Gem', 'ups And', 'xi Aql'],
      dtype=object)

In [63]:
# convert based on name:
name = 'ups And'

# only select entries with this name
mask = planets['pl_hostname'] == name
ecc = planets['pl_orbeccen'][mask]
a = planets['pl_orbsmax'][mask]
Porb = planets['pl_orbper'][mask]
Incl = planets['pl_orbincl'][mask]
sMass = planets['st_mass'][mask]
pMass = planets['pl_bmassj'][mask]

#tmax=np.array(tTime).max()
#tTime = []
#for t in planets['pl_orbtper'][mask]:
#    tTime.append([tmax,t])
tTime = planets['pl_orbtper'][mask]
    
tTime
Porb

#ecc,a

4021       4.617033
4022     241.258000
4023    1276.460000
Name: pl_orbper, dtype: float64

In [64]:
tTime

4021    2450005.368
4022    2450157.780
4023    2451347.480
Name: pl_orbtper, dtype: float64

In [65]:
planets.keys()

Index(['pl_hostname', 'pl_letter', 'pl_name', 'pl_pnum', 'pl_orbper',
       'pl_orbpererr1', 'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmax',
       'pl_orbsmaxerr1', 'pl_orbsmaxerr2', 'pl_orbsmaxlim', 'pl_orbeccen',
       'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_orbeccenlim', 'pl_orbincl',
       'pl_orbinclerr1', 'pl_orbinclerr2', 'pl_orbincllim', 'pl_bmassj',
       'pl_bmassjerr1', 'pl_bmassjerr2', 'pl_bmassjlim', 'pl_bmassprov',
       'pl_radj', 'pl_radjerr1', 'pl_radjerr2', 'pl_radjlim', 'pl_dens',
       'pl_denserr1', 'pl_denserr2', 'pl_denslim', 'pl_ttvflag', 'pl_kepflag',
       'pl_k2flag', 'pl_nnotes', 'ra_str', 'ra', 'dec_str', 'dec', 'st_dist',
       'st_disterr1', 'st_disterr2', 'st_distlim', 'gaia_dist',
       'gaia_disterr1', 'gaia_disterr2', 'gaia_distlim', 'st_teff',
       'st_tefferr1', 'st_tefferr2', 'st_tefflim', 'st_mass', 'st_masserr1',
       'st_masserr2', 'st_masslim', 'st_rad', 'st_raderr1', 'st_raderr2',
       'st_radlim', 'rowupdate', 'pl_orbtper', '

In [66]:
#planets['pl_orbtper']

In [72]:
# dict?
kepler_data = {}

#kepler_data['RowID'] = -1
kepler_data['SysName'] = name
#kepler_data['planetLetter'] = 'X'
kepler_data['NumberOfPlanets'] = len(a) 
kepler_data['Porb'] = Porb.values
#kepler_data['ePorbU']=0
#kepler_data['ePorbL']=0
kepler_data['a']=a.values
#kepler_data['ea']=0
kepler_data['ecc']=ecc.values
#kepler_data['eeccU']=0
#kepler_data['eeccL']=0
kepler_data['Incl']=Incl.values
#kepler_data['eInclU']=0  
kepler_data['pMass']=pMass.values
kepler_data['sMass']=sMass.values
kepler_data['tTime']=tTime.values
#'eInclL', 
#             'pMass',   'epMassU', 'epMassL',          'pMassType', 'sMass', 
#             'esMass',  'sRadius', 'esRadiusU',       'esRadiusL',  'tTime', 
#             'etTimeU', 'etTimeL'

In [73]:
kepler_data

{'SysName': 'ups And',
 'NumberOfPlanets': 3,
 'Porb': array([   4.617033,  241.258   , 1276.46    ]),
 'a': array([0.059222, 0.827774, 2.51329 ]),
 'ecc': array([0.0215, 0.2596, 0.2987]),
 'Incl': array([nan, nan, nan]),
 'pMass': array([0.6876, 1.981 , 4.132 ]),
 'sMass': array([1.3, 1.3, 1.3]),
 'tTime': array([2450005.368, 2450157.78 , 2451347.48 ])}

In [74]:
from convert_kepler_data import convert_kepler_data

In [75]:
star_mass, planet_masses, planet_initial_position, planet_initial_velocity, ecc = convert_kepler_data(kepler_data)

In [77]:
star_mass

1.3

In [78]:
planet_masses

array([0.6876, 1.981 , 4.132 ])

In [79]:
planet_initial_position

array([[-0.05794873,  0.        ,  0.        ],
       [-0.41464231, -0.45132958,  0.        ],
       [ 1.67133248,  0.55973363,  0.        ]])

In [80]:
planet_initial_velocity

array([[   0.        , -138.43721646,    0.        ],
       [  23.71957473,  -21.79147972,    0.        ],
       [  -5.71320164,   17.05929214,    0.        ]])

In [81]:
from kepler_data_table_to_new_planet_system import read_convert_new_system

In [82]:
filename = 'planets_2019.07.30_19.22.04.csv'

What are the possible 

In [ ]:
new_kepler_data = read_convert_new_system(filename, name)